	<footer class="d-flex justify-content-center bottom-0 p-2">
		<p class="mb-0">Copyright © <?= date('Y') ?>. All right reserved.</p>
	</footer>
	<!--end wrapper-->
	<!-- Bootstrap JS -->
	<!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script> -->
	<script src="<?= ASSETS ?>plugins/bootstrap_bundle/js/bootstrap.bundle.min.js" type="text/javascript"></script>

	<!--plugins-->
	<script src="<?= ASSETS ?>js/jquery.min.js" type="text/javascript"></script>
	<?php if (!in_array(basename($_SERVER['REQUEST_URI']), ['login', 'register', 'forgot_password'])) : ?>
		<script src="<?= ASSETS ?>plugins/jquery-knob/jquery.knob.js" type="text/javascript"></script>
		<script src="<?= ASSETS ?>plugins/notifications/js/lobibox.min.js" type="text/javascript"></script>

		<!--app JS-->
		<script src="<?= ASSETS ?>js/app.js" type="text/javascript"></script>

		<script>
			$(function() {
				$(".knob").knob();
			});
		</script>
	<?php endif ?>

	<?php if (file_exists(UPLOAD_ROOT . '\\assets\\js\\' . basename($_SERVER['REQUEST_URI']) . '.js')) : ?>
		<!--app JS-->
		<script src="<?= ASSETS ?>js/<?= basename($_SERVER['REQUEST_URI']) ?>.js" type="text/javascript"></script>
	<?php endif ?>
	</body>

	</html>