<?php $this->loadView("includes/html_header", $data); ?>

<body>
	<!-- light/dark theme switcher start -->
	<div class="position-fixed top-0 end-0 p-4 z-1">
		<?php $this->loadView("includes/theme_switcher"); ?>
	</div>
	<!-- light/dark theme switcher end -->

	<!-- wrapper -->
	<div class="d-flex min-vh-100 align-items-center justify-content-center">

		<?php flashMsg('mail_sent_fail'); ?>

		<div class="card border-light-subtle rounded-3 shadow" style="max-width: 420px;">
			<div class="card-body border-bottom text-center py-3">
				<img src="<?= ASSETS ?>images/icons/forgot-2.png" width="60" alt="" class="m-3" />
				<h2 class="text-dark-emphasis fw-bold">Forgot Password?</h2>
			</div>
			<div class="card-body">
				<p class="text-muted text-center">Enter your registered email to reset the password.</p>
				<form class="px-3" action="<?= URL_ROOT ?>user/forgot_password" method="post">
					<div class="my-4">
						<label for="inputEmailAddress" class="form-label"><small class="text-dark-emphasis fw-medium">Email</small></label>
						<input type="email" name="email" class="form-control form-control-lg <?= !empty($data['errors']['email']) ? 'is-invalid' : '' ?>" id="inputEmailAddress" placeholder="example@user.com" value="<?= $data['email'] ?>" autocomplete="email" required />
						<?php if (!empty($data['errors']['email'])) : ?>
							<span class="invalid-feedback"><?= show_errors($data['errors']['email']) ?></span>
						<?php endif ?>
					</div>
					<div class="d-grid gap-2">
						<button type="submit" class="btn btn-primary">Send</button>
						<a href="<?= URL_ROOT ?>user/login" class="btn btn-light">
							<i class='bx bx-arrow-back me-1'></i>
							Back to Login
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>
	<!-- end wrapper -->
</body>

</html>