<?php $this->loadView("includes/html_header", $data); ?>

<body>
	<!-- light/dark theme switcher start -->
	<div class="position-fixed top-0 end-0 p-4 z-1">
		<?php $this->loadView("includes/theme_switcher"); ?>
	</div>
	<!-- light/dark theme switcher end -->

	<!--wrapper-->
	<div class="d-flex flex-column min-vh-100 align-items-center justify-content-center">

		<?php
		flashMsg('registration_success');
		flashMsg('mail_sent_success');
		flashMsg('login_failed');
		?>

		<div class="card border-light-subtle rounded-3 shadow" style="max-width: 420px;">
			<div class="card-body border-bottom text-center py-3">
				<?php if (isset($data['errors']['user_not_found'])) : ?>
					<div id="flesh-msg" class="alert alert-danger text-bg-danger alert-dismissible fade show rounded-0 my-3 position-fixed top-0 start-0 end-0" roll="alert">
						<div class="d-flex justify-content-center align-items-center mx-auto" style="width: auto; min-width: 320px; max-width: 600px">
							<i class="bx bx-x-circle me-3 display-1"></i>
							<div class="d-flex flex-column align-items-start text-start">
								<h5>Login error</h5>
								<small>User with given credential not found</small>
							</div>
							<button type="button" class="btn-close position-relative align-self-start' . $close_btn . '" data-bs-dismiss="alert" aria-label="Close"></button>
						</div>
					</div>
				<?php endif ?>

				<h1 class="text-dark-emphasis fw-bold">Log in</h1>
			</div>
			<div class="card-body">
				<form class="row g-3 px-3" method="post" action="<?= URL_ROOT ?>user/login">
					<?php if (!empty($data['errors']['user'])) : ?>
						<div class="text-center">
							<span class="text-danger"><?= $data['errors']['user'] ?></span>
						</div>
					<?php endif ?>
					<div class="col-12">
						<label for="inputEmailAddress" class="form-label"><small class="text-dark-emphasis fw-medium">Email</small></label>
						<input type="email" name="email" class="form-control<?= !empty($data['errors']['email']) ? ' is-invalid' : '' ?>" id="inputEmailAddress" value="<?= $data['email'] ?>" autocomplete="username" required>
						<?php if (!empty($data['errors']['email'])) : ?>
							<span class="invalid-feedback"><?= show_errors($data['errors']['email']) ?></span>
						<?php endif ?>
					</div>
					<div class="col-12">
						<label for="inputChoosePassword" class="form-label"><small class="text-dark-emphasis fw-medium">Password</small></label>
						<div class="input-group<?= !empty($data['errors']['password']) ? ' has-validation' : '' ?>">
							<input type="password" name="password" class="form-control<?= !empty($data['errors']['password']) ? ' is-invalid' : '' ?>" id="inputChoosePassword" value="<?= $data['password'] ?>" autocomplete="current-password" required>
							<a href="javascript:;" class="input-group-text bg-transparent<?= !empty($data['errors']['password']) ? ' border-danger' : '' ?> p-0 toggle-password">
								<i toggle="#inputChoosePassword" class='bx bx-hide toggle-password-icon'></i>
							</a>

							<?php if (!empty($data['errors']['password'])) : ?>
								<span class="invalid-feedback"><?= show_errors($data['errors']['password']) ?></span>
							<?php endif ?>
						</div>
					</div>
					<div class="col-md-6 d-none">
						<div class="form-check form-switch">
							<input name="remember_me" class="form-check-input" type="checkbox" id="remember_me" <?= $data['remember_me'] == 'no' ? '' : 'checked' ?>>
							<label class="form-check-label" for="remember_me"><small class="text-dark-emphasis">Remember Me</small></label>
						</div>
					</div>
					<div class="col-md-6 text-end ms-auto"> <a href="<?= URL_ROOT ?>user/forgot_password"><small>Forgot Password?</small></a>
					</div>
					<div class="col-12 py-2">
						<div class="d-grid">
							<input type="hidden" name="csrf_token" value="<?= isset($_SESSION['csrf_token']) ? $_SESSION['csrf_token'] : '' ?>" />
							<button type="submit" class="btn btn-primary d-flex align-items-center justify-content-center px-3"><i class="bx bx-log-in-circle pe-2"></i>Log in</button>
						</div>
					</div>
				</form>
			</div>
			<div class="card-footer text-center py-4">
				<small>
					Don't have an account?
					<a href="<?= URL_ROOT ?>user/register" class="ps-1">
						<strong>Sign up here</strong>
					</a>
				</small>
			</div>
		</div>
	</div>
	<!--end wrapper-->

	<!-- Bootstrap JS -->
	<!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script> -->
	<script src="<?= ASSETS ?>plugins/bootstrap_bundle/js/bootstrap.bundle.min.js" type="text/javascript"></script>

	<!--plugins-->
	<script src="<?= ASSETS ?>js/jquery.min.js" type="text/javascript"></script>

	<!--Password show & hide js -->
	<script>
		$(document).ready(function() {
			$(".toggle-password").on("focus click keydown", function(e) {
				let code = e.keyCode || e.which;
				if ((e.type === 'click' || code === 13) && e.type !== 'keydown') {
					e.preventDefault();
					$(this).find(".toggle-password-icon").toggleClass("bx-show bx-hide");
					let input = $(this).find(".toggle-password-icon").attr("toggle");
					if ($(input).attr("type") === "password") {
						$(input).attr("type", "text");
					} else {
						$(input).attr("type", "password");
					}
				}
			});

			let myAlert = document.querySelectorAll('.toast')[0];
			if (myAlert) {
				let bsAlert = new bootstrap.Toast(myAlert, {
					autohide: false,
				});
				bsAlert.show();
			}

			// remove flesh message after 3 s
			// setTimeout(function() {
			// 	$("#flesh-msg").fadeOut(500, function() {
			// 		$(this).remove();
			// 	});
			// }, 5000);

			// localStorage.clear();
		});
	</script>
</body>

</html>