<?php $this->loadView("includes/html_header", $data); ?>

<body>
	<!--start header -->
	<?php $this->loadView("includes/header"); ?>
	<!--end header -->
	<!--wrapper-->
	<div class="container d-flex flex-column">
		<!--breadcrumb-->
		<div class="d-none d-sm-flex align-items-center px-2">
			<nav aria-label="breadcrumb">
				<ol class="breadcrumb">
					<li class="breadcrumb-item">
						<a href="<?= URL_ROOT ?>"><i class="bx bx-home-alt"></i></a>
					</li>
					<li class="breadcrumb-item active" aria-current="page">User Profile</li>
				</ol>
			</nav>
		</div>
		<?php //show($_SESSION)
		?>
		<!--end breadcrumb-->
		<!--start user profile card-->
		<div class="card border-light-subtle rounded-3 shadow mx-auto p-3" style="max-width: 540px;">
			<div class="card-body d-sm-flex">
				<div class="d-flex flex-column align-items-center fs-6 pe-sm-3 pb-sm-3 pb-sm-0" id="avatar-container">
					<label class="d-flex justify-content-between align-items-center pb-2" role="button" data-bs-toggle="tooltip" data-bs-title="Click to select new profile picture">
						<img src="<?= ASSETS . "images/avatars/" . (!empty($_SESSION['user_avatar']) ? $_SESSION['user_avatar'] : "default-user.png") ?>" class="rounded-circle p-1 mb-3 bg-primary avatar" width="120" height="120" alt="user avatar" id="avatar">
						<img src="" class="rounded-circle p-1 mb-3 bg-primary d-none" width="120" height="120" id="preview">
						<input type="file" id="avatar-upload" class="d-none" name="avatar_upload" accept="image/gif,image/jpeg,image/jpg,image/png">
					</label>
					<input type="hidden" name="csrf_token" value="<?= isset($_SESSION['csrf_token']) ? $_SESSION['csrf_token'] : '' ?>" />
					<input type="hidden" name="user_id" value="<?= isset($_SESSION['user_id']) ? $_SESSION['user_id'] : '' ?>" />
					<button type="submit" class="btn btn-outline-secondary border-0 d-flex justify-content-between align-items-center pb-2 d-none" roll="button" id="upload-avatar-btn" data-bs-toggle="modal" data-bs-target="#confirmation-modal">
						Upload
						<i class="bx bx-upload ps-2"></i>
					</button>
					<button type="submit" class="btn btn-outline-danger border-0 d-flex justify-content-between align-items-center <?= empty($_SESSION['user_avatar']) ? "d-none" : "" ?>" role="button" id="remove-avatar-btn" data-bs-toggle="modal" data-bs-target="#confirmation-modal">
						Remove
						<i class="bx bx-trash ps-2"></i>
					</button>
					<button class="btn btn-outline-warning border-0 d-flex justify-content-between align-items-center d-none" role="button" id="reset-avatar-btn">
						Cancel
						<i class="bx bx-revision bx-flip-horizontal pe-2"></i>
					</button>
				</div>
				<hr class="d-block d-sm-none">
				<div class="d-block ps-sm-3">
					<ul class="nav nav-tabs nav-fill justify-content-center" id="userProfile" role="tablist">
						<li class="nav-item" role="presentation">
							<button class="nav-link text-uppercase active" id="user-info" data-bs-toggle="tab" data-bs-target="#user-info-pane" type="button" role="tab" aria-controls="user-info-pane" aria-selected="true">
								<small class="fw-medium">User info</small>
							</button>
						</li>
						<li class="nav-item" role="presentation">
							<button class="nav-link text-uppercase" id="password-tab" data-bs-toggle="tab" data-bs-target="#password-tab-pane" type="button" role="tab" aria-controls="password-tab-pane" aria-selected="false">
								<small class="fw-medium">Password</small>
							</button>
						</li>
					</ul>
					<div class="tab-content px-2 pt-3" id="userProfileContent">
						<div class="tab-pane fade show active" id="user-info-pane" role="tabpanel" aria-labelledby="user-info" tabindex="0">
							<form class="row g-3" id="updateUserInfoForm" action="<?= URL_ROOT ?>user/updateProfile" method="post">
								<div class="col-12">
									<label for="inputFirstName" class="form-label"><small class="text-dark-emphasis fw-medium">First Name</small></label>
									<input type="text" name="user_name" class="form-control" id="inputFirstName" value="<?= $_SESSION['user_name'] ?>" autocomplete="given-name" required>
									<span class="invalid-feedback"></span>
								</div>
								<div class="col-12">
									<label for="inputLastName" class="form-label"><small class="text-dark-emphasis fw-medium">Last Name</small></label>
									<input type="text" name="user_lastname" class="form-control" id="inputLastName" value="<?= $_SESSION['user_lastname'] ?>" autocomplete="family-name" required>
									<span class="invalid-feedback"></span>
								</div>
								<div class="col-12">
									<label for="inputEmailAddress" class="form-label"><small class="text-dark-emphasis fw-medium">Email</small></label>
									<input type="email" name="user_email" class="form-control" id="inputEmailAddress" value="<?= $_SESSION['user_email'] ?>" autocomplete="email" required>
									<span class="invalid-feedback"></span>
								</div>
								<div class="col-12 pt-2">
									<input type="hidden" name="csrf_token" value="<?= isset($_SESSION['csrf_token']) ? $_SESSION['csrf_token'] : '' ?>" />
									<button type="submit" class="btn btn-primary float-end" disabled><i class='bx bx-cog pe-2'></i>Save user</button>
								</div>
							</form>
						</div>
						<div class="tab-pane fade" id="password-tab-pane" role="tabpanel" aria-labelledby="password-tab" tabindex="0">
							<form class="row g-3" id="updatePasswordForm" action="<?= URL_ROOT ?>user/updatePassword" method="post">
								<div class="col-12">
									<label for="inputOldPassword" class="form-label"><small class="text-dark-emphasis fw-medium">Old Password</small></label>
									<div class="input-group has-validation">
										<input id="inputOldPassword" type="password" class="form-control" name="old_password" autocomplete="current-password" required>
										<a href="javascript:;" class="input-group-text bg-transparent p-0 toggle-password">
											<i toggle=" #inputOldPassword" class='bx bx-hide toggle-password-icon'></i>
										</a>
										<span class="invalid-feedback"></span>
									</div>
								</div>
								<div class="col-12">
									<label for="inputChoosePassword" class="form-label"><small class="text-dark-emphasis fw-medium">New Password</small></label>
									<div class="input-group has-validation">
										<input id="inputChoosePassword" type="password" class="form-control" name="password" autocomplete="new-password" required>
										<a href="javascript:;" class="input-group-text bg-transparent p-0 toggle-password">
											<i toggle="#inputChoosePassword" class='bx bx-hide toggle-password-icon'></i>
										</a>
										<span class="invalid-feedback"></span>
									</div>
								</div>
								<div class="col-12">
									<label for="inputConfirmPassword" class="form-label"><small class="text-dark-emphasis fw-medium">Confirm New Password</small></label>
									<div class="input-group has-validation">
										<input id="inputConfirmPassword" type="password" class="form-control" name="confirm_password" autocomplete="new-password" required>
										<a href="javascript:;" class="input-group-text bg-transparent p-0 toggle-password">
											<i toggle="#inputConfirmPassword" class='bx bx-hide toggle-password-icon'></i>
										</a>
										<span class="invalid-feedback"></span>
									</div>
								</div>
								<div class="col-12 pt-2">
									<input type="hidden" name="csrf_token" value="<?= isset($_SESSION['csrf_token']) ? $_SESSION['csrf_token'] : '' ?>" />
									<button type="submit" class="btn btn-primary float-end" disabled><i class='bx bx-cog pe-2'></i>Save password</button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div id="confirmation-modal" class="modal" tabindex="-1">
		<div class="modal-dialog modal-dialog-centered">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title"></h5>
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="modal-body">
					<p></p>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
					<button type="button" class="btn d-none" id="confirm-btn"></button>
				</div>
			</div>
		</div>
	</div>
	<!--end wrapper-->
	<?php $this->loadView("includes/footer", $data); ?>