<?php $this->loadView("includes/html_header", $data); ?>

<body>
	<!-- light/dark theme switcher start -->
	<div class="position-fixed top-0 end-0 p-4 z-1">
		<?php $this->loadView("includes/theme_switcher"); ?>
	</div>
	<!-- light/dark theme switcher end -->

	<!--wrapper-->
	<div class="d-flex min-vh-100 align-items-center justify-content-center">

		<?php flashMsg('registration_failed'); ?>

		<div class="card border-light-subtle rounded-3 shadow" style="max-width: 450px;">
			<div class="card-body border-bottom text-center py-3">
				<h1 class="text-dark-emphasis fw-bold">Sign Up</h1>
			</div>

			<div class="card-body">
				<form class="row g-3 px-3" action="<?= URL_ROOT ?>user/register" method="post">
					<div class="col-sm-6">
						<label for="inputFirstName" class="form-label"><small class="text-dark-emphasis fw-medium">First Name</small></label>
						<input type="text" name="name" class="form-control<?= !empty($data['errors']['name']) ? ' is-invalid' : '' ?>" id="inputFirstName" placeholder="Jhon" value="<?= $data['name'] ?>" autocomplete="given-name" required>
						<?php if (!empty($data['errors']['name'])) : ?>
							<span class="invalid-feedback"><?= show_errors($data['errors']['name']) ?></span>
						<?php endif ?>
					</div>
					<div class="col-sm-6">
						<label for="inputLastName" class="form-label"><small class="text-dark-emphasis fw-medium">Last Name</small></label>
						<input type="text" name="lastname" class="form-control<?= !empty($data['errors']['lastname']) ? ' is-invalid' : '' ?>" id="inputLastName" placeholder="Doe" value="<?= $data['lastname'] ?>" autocomplete="family-name" required>
						<?php if (!empty($data['errors']['lastname'])) : ?>
							<span class="invalid-feedback"><?= show_errors($data['errors']['lastname']) ?></span>
						<?php endif ?>
					</div>
					<div class="col-12">
						<label for="inputEmailAddress" class="form-label"><small class="text-dark-emphasis fw-medium">Email</small></label>
						<input type="email" name="email" class="form-control<?= !empty($data['errors']['email']) ? ' is-invalid' : '' ?>" id="inputEmailAddress" placeholder="example@user.com" value="<?= $data['email'] ?>" autocomplete="email" required>
						<?php if (!empty($data['errors']['email'])) : ?>
							<span class="invalid-feedback"><?= show_errors($data['errors']['email']) ?></span>
						<?php endif ?>
					</div>
					<div class="col-12">
						<label for="inputChoosePassword" class="form-label"><small class="text-dark-emphasis fw-medium">Password</small></label>
						<div class="input-group<?= !empty($data['errors']['password']) ? ' has-validation' : '' ?>">
							<input id="inputChoosePassword" type="password" class="form-control<?= !empty($data['errors']['password']) ? ' is-invalid' : '' ?>" name="password" placeholder="Enter Password" value="<?= $data['password'] ?>" autocomplete="new-password" required>
							<a href="javascript:;" class="input-group-text bg-transparent<?= !empty($data['errors']['password']) ? ' border-danger' : '' ?> p-0 toggle-password">
								<i toggle="#inputChoosePassword" class='bx bx-hide toggle-password-icon'></i>
							</a>
							<?php if (!empty($data['errors']['password'])) : ?>
								<span class="invalid-feedback"><?= show_errors($data['errors']['password']) ?></span>
							<?php endif ?>
						</div>
					</div>
					<div class="col-12">
						<label for="inputConfirmPassword" class="form-label"><small class="text-dark-emphasis fw-medium">Confirm Password</small></label>
						<div class="input-group<?= !empty($data['errors']['confirm_password']) ? ' has-validation' : '' ?>">
							<input id="inputConfirmPassword" type="password" class="form-control<?= !empty($data['errors']['confirm_password']) ? ' is-invalid' : '' ?>" name="confirm_password" placeholder="Confirm Password" value="<?= $data['confirm_password'] ?>" autocomplete="new-password" required>
							<a href="javascript:;" class="input-group-text bg-transparent<?= !empty($data['errors']['confirm_password']) ? ' border-danger' : '' ?> p-0 toggle-password">
								<i toggle="#inputConfirmPassword" class='bx bx-hide toggle-password-icon'></i>
							</a>
							<?php if (!empty($data['errors']['confirm_password'])) : ?>
								<span class="invalid-feedback"><?= show_errors($data['errors']['confirm_password']) ?></span>
							<?php endif ?>
						</div>
					</div>
					<div class="col-12">
						<div class="form-check form-switch">
							<input name="term_and_cond" class="form-check-input<?= isset($data['errors']['term_and_cond']) ? ' is-invalid' : '' ?>" type="checkbox" roll="switch" id="term_and_cond" <?= $data['term_and_cond'] === '' ? '' : 'checked' ?>>
							<label class="form-check-label" for="term_and_cond"><small class="text-dark-emphasis">I read and agree to Terms & Conditions</small></label>
							<?php if (isset($data['errors']['term_and_cond'])) : ?>
								<span class="invalid-feedback"><?= show_errors($data['errors']['term_and_cond']) ?></span>
							<?php endif ?>
						</div>
					</div>
					<div class="col-12 py-2">
						<div class="d-grid">
							<input type="hidden" name="csrf_token" value="<?= isset($_SESSION['csrf_token']) ? $_SESSION['csrf_token'] : '' ?>" />
							<button type="submit" class="btn btn-primary d-flex align-items-center justify-content-center"><i class='bx bx-user pe-2'></i>Sign up</button>
						</div>
					</div>
				</form>
			</div>
			<div class="card-footer text-center py-4">
				<small>
					Already have an account?
					<a href="<?= URL_ROOT ?>user/login" class="ps-1">
						<strong>Log in here</strong>
					</a>
				</small>
			</div>
		</div>
	</div>


	<!--end wrapper-->

	<!-- Bootstrap JS -->
	<!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script> -->
	<script src="<?= ASSETS ?>plugins/bootstrap_bundle/js/bootstrap.bundle.min.js" type="text/javascript"></script>

	<!--plugins-->
	<script src="<?= ASSETS ?>js/jquery.min.js" type="text/javascript"></script>

	<!--Password show & hide js -->
	<script>
		$(document).ready(function() {
			$(".toggle-password").on("focus click keydown", function(e) {
				let code = e.keyCode || e.which;
				if ((e.type === 'click' || code === 13) && e.type !== 'keydown') {
					e.preventDefault();
					$(this).find(".toggle-password-icon").toggleClass("bx-show bx-hide");
					let input = $(this).find(".toggle-password-icon").attr("toggle");
					if ($(input).attr("type") === "password") {
						$(input).attr("type", "text");
					} else {
						$(input).attr("type", "password");
					}
				}
			});

			$("#term_and_cond").on("focus click keydown", function(e) {
				let code = e.keyCode || e.which;
				if ((e.type === 'click' || code === 13) && e.type !== 'keydown') {
					let input = $(this).prop("checked") ? true : false;
					$(this).prop("checked", input);

					$(this).siblings(".invalid-feedback").length > 0 && $(this).toggleClass("is-invalid");
				}

			});
		});
	</script>
</body>

</html>