<!DOCTYPE html>
<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!--favicon
	<link rel="icon" href="<?= ASSETS ?>/images/favicon-32x32.png" type="image/png" />-->
	<!-- loader-->
	<link href="<?= ASSETS ?>plugins/pace/pace.min.css" rel="stylesheet" type="text/css" />
	<script src="<?= ASSETS ?>plugins/pace/pace.min.js" type="text/javascript"></script>
	<!-- Bootstrap CSS -->
	<link href="<?= ASSETS ?>plugins/bootstrap_bundle/css/bootstrap.min.css" rel="stylesheet" type="text/css">
	<link href="<?= ASSETS ?>css/icons.css" rel="stylesheet" type="text/css">
	<link href="<?= ASSETS ?>css/app.css" rel="stylesheet" type="text/css">
	<title>404 error</title>
</head>

<body>
	<!-- wrapper -->
	<div class="position-relative w-full">
		<nav class="navbar navbar-expand-md bg-body border-bottom mb-3 p-0">
			<div class="container">
				<button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="d-flex fs-1 lh-1 p-2 text-dark text-decoration-none" style="font-weight: 500;">
					<div class="text-body">T</div>
					<div class="d-flex flex-column">
						<div class="text-body">in</div>
						<div class="text-info fw-bold align-self-end" style="line-height: 0.7rem; margin-top: -0.3rem; margin-right:-0.25rem; font-size: calc((1.375rem + 1.5vw)*0.3)">MVC</div>
					</div>
					<div class="text-body">y</div>
				</div>

				<div class="vr d-none d-md-block"></div>

				<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
					<div class="offcanvas-header">
						<div class="d-flex fs-1 lh-1 p-2 text-dark text-decoration-none" style="font-weight: 500;">
							<div class="text-body">T</div>
							<div class="d-flex flex-column">
								<div class="text-body">in</div>
								<div class="text-info fw-bold align-self-end" style="line-height: 0.7rem; margin-top: -0.3rem; margin-right:-0.25rem; font-size: calc((1.375rem + 1.5vw)*0.3)">MVC</div>
							</div>
							<div class="text-body">y</div>
						</div>
						<button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
					</div>
					<div class="offcanvas-body align-items-center ">
						<ul class="navbar-nav ms-auto mb-2 mb-sm-0">
							<li class="nav-item">
								<a class="nav-link" aria-current="page" href="<?= URL_ROOT ?>">Home</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" aria-current="page" href="<?= URL_ROOT ?>user/login">Login</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" aria-current="page" href="<?= URL_ROOT ?>user/register">Register</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</nav>
		<div class="d-flex align-items-center justify-content-center">
			<div class="container">
				<div class="card py-5">
					<div class="row g-0">
						<div class="col col-xl-5">
							<div class="card-body p-4">
								<h1 class="display-1"><span class="text-primary">4</span><span class="text-danger">0</span><span class="text-success">4</span></h1>
								<h2 class="font-weight-bold display-4">Lost in Space</h2>
								<p>You have reached the edge of the universe.
									<br>The page you requested could not be found.
									<br>Don't worry and return to the previous page.
								</p>
								<div class="mt-5"> <a href="<?= URL_ROOT ?>home" class="btn btn-primary btn-lg px-md-5 radius-30">Go Home</a>
									<a href="javascript:history.back();" class="btn btn-outline-dark btn-lg ms-3 px-md-5 radius-30">Back</a>
								</div>
							</div>
						</div>
						<div class="col-xl-7">
							<img src="<?= ASSETS ?>images/errors-images/404-error.png" class="img-fluid" alt="">
						</div>
					</div>
					<!--end row-->
				</div>
			</div>
		</div>
		<div class="bg-white p-3 fixed-bottom border-top shadow">
			<div class="d-flex align-items-center justify-content-center flex-wrap">
				<p class="mb-0">Copyright © <?= date('Y') ?>. All right reserved.</p>
			</div>
		</div>
	</div>
	<!-- end wrapper -->
	<!-- Bootstrap JS -->
	<script src="<?= ASSETS ?>plugins/bootstrap_bundle/js/bootstrap.bundle.min.js" type="text/javascript"></script>
</body>

</html>